# Demonstration of using JsonOutputParser to get raw JSON formatted data output from an LLM
from langchain_core.output_parsers import JsonOutputParser  # Import JsonOutputParser class
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint  # Import Hugging Face model classes
from dotenv import load_dotenv  # Import load_dotenv to load environment variables from .env file
from langchain_core.prompts import PromptTemplate  # Import PromptTemplate class

load_dotenv()  # Load environment variables (e.g. Hugging Face token)

# Initialize Hugging Face Endpoint specifying model repository and task
llm = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen2.5-7B-Instruct",
    task="text-generation"
)

# Wrap Hugging Face endpoint in ChatHuggingFace model
model = ChatHuggingFace(llm=llm)

# Instantiate JsonOutputParser to enforce JSON output format
parser = JsonOutputParser()

# Create PromptTemplate injecting JSON format instructions generated by parser
template = PromptTemplate(
    template='Give me 5 facts about the {topic} \n {format_instruction}',
    input_variables=['topic'],
    partial_variables={'format_instruction': parser.get_format_instructions()}
)

# Combine PromptTemplate, Model, and JsonOutputParser into an LCEL chain
chain = template | model | parser

# Invoke chain with input topic question
result = chain.invoke({'topic': 'What happen when India become Superpower?'})

# Print the resulting JSON dictionary output
print(result)