# Demonstration of parsing LLM text output into structured Pydantic model objects
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint  # Import Hugging Face model classes
from dotenv import load_dotenv  # Import load_dotenv to read environment variables from .env file
from langchain_core.prompts import PromptTemplate  # Import PromptTemplate class
from langchain_core.output_parsers import PydanticOutputParser  # Import Pydantic parser class
from pydantic import BaseModel, Field  # Import Pydantic schema definition tools

load_dotenv()  # Load environment variables (e.g. HuggingFace token)

# Initialize Hugging Face endpoint specifying model repo and text generation task
llm = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen2.5-7B-Instruct",
    task="text-generation"
)

# Wrap Hugging Face endpoint in a ChatHuggingFace model
model = ChatHuggingFace(llm=llm)

# Define target Pydantic data model schema with validation constraints
class Person(BaseModel):
    name: str = Field(description='Name of the Person')
    age: int = Field(gt=18, description='Age of the Person')
    city: str = Field(description='Name of the city the Person belongs to')

# Instantiate PydanticOutputParser bound to the Person data schema
parser = PydanticOutputParser(pydantic_object=Person)

# Create PromptTemplate injecting format instructions generated by the parser
template = PromptTemplate(
    template='Generate the name, age and city of the fictional {place} person \n {format_instruction}',
    input_variables=['place'],
    partial_variables={'format_instruction': parser.get_format_instructions()}
)

# Combine PromptTemplate, Chat Model, and Output Parser into a single LCEL chain
chain = template | model | parser

# Invoke chain with input variable 'place'
final_result = chain.invoke({'place': 'Indian'})

# Print the parsed Pydantic object result
print(final_result)