# Demonstration of using StructuredOutputParser and ResponseSchema to extract multiple named fields from an LLM
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint  # Import Hugging Face model classes
from dotenv import load_dotenv  # Import load_dotenv to load environment variables from .env file
from langchain_core.prompts import PromptTemplate  # Import PromptTemplate class
from langchain_classic.output_parsers import StructuredOutputParser, ResponseSchema  # Import structured parser and response schema classes

load_dotenv()  # Load environment variables (e.g. Hugging Face token)

# Initialize Hugging Face Endpoint specifying model repository and task
llm = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen2.5-7B-Instruct",
    task="text-generation"
)

# Wrap Hugging Face endpoint in ChatHuggingFace model
model = ChatHuggingFace(llm=llm)

# Define response schemas specifying expected key names and field descriptions
schema = [
    ResponseSchema(name='Fact_1', description='fact 1 about the topic'),
    ResponseSchema(name='Fact_2', description='fact 2 about the topic'),
    ResponseSchema(name='Fact_3', description='fact 3 about the topic'),
]

# Create StructuredOutputParser from the list of response schemas
parser = StructuredOutputParser.from_response_schemas(schema)

# Create PromptTemplate injecting format instructions generated by parser
template = PromptTemplate(
    template='Give me 3 fact about {topic} \n {format_instruction}',
    input_variables=['topic'],
    partial_variables={'format_instruction': parser.get_format_instructions()}
)

# Build LCEL chain: template -> model -> parser
chain = template | model | parser

# Invoke chain with input topic 'Indian'
result = chain.invoke({'topic': 'Indian'})

# Print the structured dictionary output containing Fact_1, Fact_2, Fact_3 keys
print(result)